
logging:
  level:
    ROOT: INFO
    jasper: DEBUG
    org:
      springframework:
        security: DEBUG
        integration: DEBUG
        web: DEBUG
        cors: DEBUG
    io:
      fabric8: DEBUG
